/**
 * Created by hxsd on 2016/6/6.
 */
//创建主模块
var loveAmoy = angular.module("loveAmoy",["ionic"]);
//配置路由
loveAmoy.config(function ($stateProvider,$urlRouterProvider) {
    //选项卡页面
    $stateProvider.state("tabs",{
        url:"/tabs",
        abstract:true,
        templateUrl:"views/tabs/tabs.html"
    });
    //首页
    $stateProvider.state("tabs.home",{
        url:"/home",
        views:{
            "tab-home":{templateUrl:"views/home/home.html",
            controller:"homeCtrl"
            }
        }
    });
    //微淘
    $stateProvider.state("tabs.microTao",{
        url:"/microTao",
        views:{
            "tab-microTao":{templateUrl:"views/microTao/microTao.html"}
        }
    });
    //发现
    $stateProvider.state("tabs.find",{
        url:"/find",
        views:{
            "tab-find":{templateUrl:"views/find/find.html"}
        }
    });
    //购物车
    $stateProvider.state("tabs.cart",{
        url:"/cart",
        views:{
            "tab-cart":{templateUrl:"views/cart/cart.html"}
        }
    });
    //我的爱淘
    $stateProvider.state("tabs.myLoveAmoy",{
        url:"/myLoveAmoy",
        views:{
            "tab-myLoveAmoy":{templateUrl:"views/myLoveAmoy/myLoveAmoy.html"}
        }
    });
    //引导页
    $stateProvider.state("LoveAmoy",{
        url:"/LoveAmoy",
       templateUrl:"views/LoveAmoy/LoveAmoy.html",
        controller:"LoveAmoyCtrl"
    });
    //默认页 最终修改为引导页
    $urlRouterProvider.otherwise("/LoveAmoy");
});
